name: Ci job 

on: push


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: printing date
        run: date
  job2:
    runs-on: windows-latest
    needs: [job1]
    steps:
      - name: printing date
        run: Get-date

  job3:
    runs-on: macos-latest
    needs: [job1, job2]
    steps:
      - name: printinf date
        run: date
  job4:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: printing date
        run: date